In [88]:
from keras.models import Sequential
from keras.layers.core import Dense
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

import pandas as pd
import numpy
import tensorflow as tf

# seed 값 설정
seed = 0
numpy.random.seed(seed)
tf.random.set_seed(3)

In [110]:
# 데이터 로드 및 확인
df = pd.read_csv('../dataset/sonar.csv', header=None)

print(df.shape)
df.head(3)

(208, 61)


0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   R  

[3 rows x 61 columns]

In [111]:
df[60].value_counts()

M    111
R     97
Name: 60, dtype: int64

In [112]:
dataset = df.values
# 피처 데이터, 타깃 데이터 분리
X = dataset[:, 0:60]
Y_obj = dataset[:, 60]

In [113]:
# 원핫 인코딩
e = LabelEncoder()
e.fit(Y_obj)
Y = e.transform(Y_obj)

# 학습 셋과 테스트 셋의 구분
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=seed)

In [114]:
# X_train 피처는 'float32' 타입으로 만들어줘야 학습이 가능
X_train = np.asarray(X_train).astype('float32')
X_train

array([[0.0135, 0.0045, 0.0051, ..., 0.0028, 0.003 , 0.003 ],
       [0.0293, 0.0644, 0.039 , ..., 0.016 , 0.0095, 0.0011],
       [0.024 , 0.0218, 0.0324, ..., 0.0019, 0.0066, 0.0023],
       ...,
       [0.0228, 0.0106, 0.013 , ..., 0.0045, 0.0063, 0.0039],
       [0.0373, 0.0281, 0.0232, ..., 0.0054, 0.0085, 0.006 ],
       [0.018 , 0.0444, 0.0476, ..., 0.005 , 0.0073, 0.0022]],
      dtype=float32)

In [115]:
# X_test 피처도 'float32' 타입으로 만들어준다.
X_test = np.asarray(X_test).astype('float32')
X_test

array([[7.90e-03, 8.60e-03, 5.50e-03, ..., 5.80e-03, 5.90e-03, 3.20e-03],
       [2.29e-02, 3.69e-02, 4.00e-03, ..., 2.90e-03, 1.04e-02, 1.63e-02],
       [4.42e-02, 4.77e-02, 4.90e-03, ..., 1.05e-02, 5.90e-03, 1.05e-02],
       ...,
       [3.15e-02, 2.52e-02, 1.67e-02, ..., 3.50e-03, 1.00e-04, 5.50e-03],
       [4.28e-02, 5.55e-02, 7.08e-02, ..., 8.40e-03, 1.13e-02, 4.90e-03],
       [2.39e-02, 1.89e-02, 4.66e-02, ..., 2.60e-03, 3.60e-03, 2.40e-03]],
      dtype=float32)

In [116]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(145, 60)
(63, 60)
(145,)
(63,)


In [117]:
X_train

array([[0.0135, 0.0045, 0.0051, ..., 0.0028, 0.003 , 0.003 ],
       [0.0293, 0.0644, 0.039 , ..., 0.016 , 0.0095, 0.0011],
       [0.024 , 0.0218, 0.0324, ..., 0.0019, 0.0066, 0.0023],
       ...,
       [0.0228, 0.0106, 0.013 , ..., 0.0045, 0.0063, 0.0039],
       [0.0373, 0.0281, 0.0232, ..., 0.0054, 0.0085, 0.006 ],
       [0.018 , 0.0444, 0.0476, ..., 0.005 , 0.0073, 0.0022]],
      dtype=float32)

In [118]:
Y_train

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0])

In [119]:
# 모델 정의
model = Sequential()                                    
model.add(Dense(24,  input_dim=60, activation='relu'))  # 입력층 노드 수 60개(relu)
                                                        # 은닉층1 노드 수 24개(relu)
model.add(Dense(10, activation='relu'))                 # 은닉층2 노드 수 10개(relu)
model.add(Dense(1, activation='sigmoid'))               # 출력층 노드 수 1개(sigmoid로 이진 분류)

model.compile(loss='binary_crossentropy',
            optimizer='adam',
            metrics=['accuracy'])

In [120]:
# 모델 학습
model.fit(X_train, Y_train, epochs=130, batch_size=5)

Epoch 1/130
29/29 [==============================] - 0s 744us/step - loss: 0.7022 - accuracy: 0.4759
Epoch 2/130
29/29 [==============================] - 0s 727us/step - loss: 0.6870 - accuracy: 0.5448
Epoch 3/130
29/29 [==============================] - 0s 780us/step - loss: 0.6774 - accuracy: 0.5586
Epoch 4/130
29/29 [==============================] - 0s 739us/step - loss: 0.6614 - accuracy: 0.6276
Epoch 5/130
29/29 [==============================] - 0s 668us/step - loss: 0.6484 - accuracy: 0.7172
Epoch 6/130
29/29 [==============================] - 0s 777us/step - loss: 0.6365 - accuracy: 0.6966
Epoch 7/130
29/29 [==============================] - 0s 878us/step - loss: 0.6165 - accuracy: 0.6828
Epoch 8/130
29/29 [==============================] - 0s 821us/step - loss: 0.5939 - accuracy: 0.7517
Epoch 9/130
29/29 [==============================] - 0s 822us/step - loss: 0.5688 - accuracy: 0.7241
Epoch 10/130
29/29 [==============================] - 0s 783us/step - loss: 0.5470 - accura

29/29 [==============================] - 0s 711us/step - loss: 0.1090 - accuracy: 0.9793
Epoch 82/130
29/29 [==============================] - 0s 775us/step - loss: 0.1240 - accuracy: 0.9655
Epoch 83/130
29/29 [==============================] - 0s 606us/step - loss: 0.1201 - accuracy: 0.9586
Epoch 84/130
29/29 [==============================] - 0s 752us/step - loss: 0.1066 - accuracy: 0.9793
Epoch 85/130
29/29 [==============================] - 0s 704us/step - loss: 0.0986 - accuracy: 0.9862
Epoch 86/130
29/29 [==============================] - 0s 676us/step - loss: 0.0984 - accuracy: 0.9793
Epoch 87/130
29/29 [==============================] - 0s 817us/step - loss: 0.0943 - accuracy: 0.9793
Epoch 88/130
29/29 [==============================] - 0s 653us/step - loss: 0.0936 - accuracy: 0.9862
Epoch 89/130
29/29 [==============================] - 0s 617us/step - loss: 0.0881 - accuracy: 0.9931
Epoch 90/130
29/29 [==============================] - 0s 673us/step - loss: 0.0958 - accuracy: 

In [122]:
# 테스트셋에 모델 적용
print("\n Test Accuracy: %.4f" % (model.evaluate(X_test, Y_test)[1]))

2/2 [==============================] - 0s 859us/step - loss: 0.7783 - accuracy: 0.8413

 Test Accuracy: 0.8413
